#!/bin/bash

path="chart-1"
commits=$(git rev-list $(echo $(git log -L5,5:$path/Chart.yaml -n 1 --no-abbrev-commit) | awk '{print $2}')..HEAD)

major_version=()
minor_version=()
patch=()
other=()
# for c in $commits ; do
for c in "refactor: what the heck" "fix: blah" "feat: This is a feature" "docs(asdf): this is a docs change" "build(sdf): This is a deployable unit" "fix!: So is this" ; do
    # message=$(git log -n 1 --pretty=format:%s $c)
    # commit_list+=( $message )

    if [[ "$c" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\!)?(\(.*\)(\!)?)?\: ]]; then
        match_string=$( echo "${BASH_REMATCH%?}" )
        if [[ "$c" =~ [[:space:]].*$ ]]; then
            commit_string=$( echo "${BASH_REMATCH}" | xargs )
            case $match_string in
                *docs* | *build* | *!)
                    echo "Major Version: $commit_string"
                    ;;
                *feat*)
                    echo "Minor Version: $commit_string"
                    ;;
                *fix* | *refactor*)
                    other+="$commit_string [(${})]()"
                    ;;
                *)
                    other+=("$commit_string [()]()")
                    echo "Other: $commit_string"
                    ;;
            esac
        fi
    fi
done